/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscador;

import java.sql.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.TOP;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class catalogo extends javax.swing.JFrame {
    
    DefaultTableModel tabla;
    public static int columna,fila;
    conexion c=new conexion();
        Statement st;
        Connection conet;
        ResultSet rs;
         JButton boton1=new JButton("detalles");
        
    

    /**
     * Creates new form catalogo
     */
    public catalogo() {
       inicio();
        initComponents();
        setLocationRelativeTo(null);
        tabla_libros.setEnabled(false);
        tabla_libros.setDefaultRenderer(Object.class, new boton_detalle());
        String[] id={"id","autor","titulo","fecha de publicacion","categoria","detalles"};
    tabla=new DefaultTableModel();
    tabla_libros.setRowHeight(20);
    tabla.setColumnIdentifiers(id);
    tabla_libros.setModel(tabla);
    String sql="select * from libros;";
    consultar(sql);
      RESULTADO_label.setText("");
      RESULTADOS_BUSQUEDA_R.setText("");
    }
void inicio(){
this.setTitle("catalogo");
this.setResizable(false);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_libros = new javax.swing.JTable();
        area_texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscador = new javax.swing.JToggleButton();
        boton_reiniciar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        RESULTADOS_BUSQUEDA_E = new javax.swing.JLabel();
        RESULTADO_label = new javax.swing.JLabel();
        RESULTADOS_BUSQUEDA_R = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_libros.setAutoCreateRowSorter(true);
        tabla_libros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabla_libros.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabla_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_libro", "titulo", "autor", "fecha_publicacion", "editorial", "detalle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_libros.setToolTipText("");
        tabla_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_librosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_libros);
        if (tabla_libros.getColumnModel().getColumnCount() > 0) {
            tabla_libros.getColumnModel().getColumn(0).setResizable(false);
            tabla_libros.getColumnModel().getColumn(1).setResizable(false);
            tabla_libros.getColumnModel().getColumn(2).setResizable(false);
            tabla_libros.getColumnModel().getColumn(3).setResizable(false);
            tabla_libros.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 620, 390));

        area_texto.setForeground(new java.awt.Color(204, 204, 204));
        area_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_textoActionPerformed(evt);
            }
        });
        jPanel2.add(area_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 510, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("CATALOGO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        buscador.setBackground(new java.awt.Color(0, 204, 204));
        buscador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscador.setForeground(new java.awt.Color(255, 255, 255));
        buscador.setText("BUSCAR");
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        jPanel2.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 37));

        boton_reiniciar.setBackground(new java.awt.Color(0, 204, 204));
        boton_reiniciar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        boton_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        boton_reiniciar.setText("REINICIAR");
        boton_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_reiniciarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 100, 40));

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));
        jPanel4.setForeground(new java.awt.Color(0, 51, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESULTADOS_BUSQUEDA_E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscador/images.jpeg"))); // NOI18N
        jPanel4.add(RESULTADOS_BUSQUEDA_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 299, 270));

        RESULTADO_label.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(RESULTADO_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        RESULTADOS_BUSQUEDA_R.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(RESULTADOS_BUSQUEDA_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 280, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_area_textoActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        reiniciar();
        String busqueda=area_texto.getText();
         String sql="SELECT * \n FROM libros \n WHERE (titulo LIKE '%"+busqueda+"%')\n OR (autor LIKE '%"+busqueda+"%')\n OR (fecha_publicacion LIKE '%"+busqueda+"%');";
        consultar(sql);
        
    }//GEN-LAST:event_buscadorActionPerformed

    private void boton_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_reiniciarActionPerformed
       
       area_texto.setText("");
      
       reiniciar();
       RESULTADO_label.setText("");
      RESULTADOS_BUSQUEDA_R.setText("");
    }//GEN-LAST:event_boton_reiniciarActionPerformed

    private void tabla_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_librosMouseClicked
        
        columna=tabla_libros.getColumnModel().getColumnIndexAtX(evt.getX());
        fila=evt.getY()/tabla_libros.getRowHeight();
        if(columna<=tabla_libros.getColumnCount()&&columna>=0 &&fila<=tabla_libros.getRowCount()&&fila>=0){
            Object objet=tabla_libros.getValueAt(fila, columna);
            if(objet instanceof JButton){
            String t= String.valueOf(tabla_libros.getValueAt(fila, 0));
            detalles de=new detalles();
            de.setDato(t);
            de.setVisible(true);
            this.setVisible(false);
            
            }
    }
        
        
    }//GEN-LAST:event_tabla_librosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogo().setVisible(true);
            }
        });
    }
    void reiniciar(){
    String sql="select * from libros;";
    consultar(sql);
    }
    
    
     void consultar(String sql) {
   tabla.setRowCount(0);
    try {
        conet=c.getConexion();
        st=conet.createStatement();
        rs=st.executeQuery(sql);
        Object[]f=new Object[6];
        while (rs.next()) {        
        f[0]=rs.getInt("id_libro");
        f[1]=rs.getString("titulo");
        f[2]=rs.getString("autor");
        f[3]=rs.getString("fecha_publicacion");
        f[4]=rs.getString("categoria");;
        f[5]=boton1;
        tabla.addRow(f);
    }
        if(tabla.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "no hay resultados");
            reiniciar();
            area_texto.setText("");
         
        } else {
            RESULTADO_label.setText("RESULTADOS DE LA BUSQUEDA");
            RESULTADOS_BUSQUEDA_R.setText(String.valueOf(tabla.getRowCount()));
          tabla_libros.setModel(tabla);
        }
        
  
    } catch (Exception e) {
    }
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RESULTADOS_BUSQUEDA_E;
    private javax.swing.JLabel RESULTADOS_BUSQUEDA_R;
    private javax.swing.JLabel RESULTADO_label;
    private javax.swing.JTextField area_texto;
    private javax.swing.JButton boton_reiniciar;
    private javax.swing.JToggleButton buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_libros;
    // End of variables declaration//GEN-END:variables
}
